### ISSUE TITLE
Error when copying benchmark data to `kitti_raw_sync`

### ISSUE THREAD

**Issue by gmberton** [jspenmar/monodepth_benchmark#1]
Hello, thank you for the amazing work!
I am downloading the dataset following the instructions on `https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md`.
In the Download section of Kitti Depth Benchmark it says to execute
`python ../../api/data/export_kitti_depth_benchmark.py  # Copy benchmark data to 'kitti_raw_sync'`
When I run that I get a `ModuleNotFoundError: No module named 'src'`.
If I move to the root and try to run the script as a module I get a KeyError.
How can I solve that?
![asdf](https://user-images.githubusercontent.com/49533159/193255882-b8fd3224-0be2-4dca-bd44-226900892fd3.png)

**Comment by jspenmar** [comment]
Hi, thanks for the interest! 

The `ModuleNotFound` error should be solvable by adding the repo path to your `PYTHONPATH` (see instructions [here](https://github.com/jspenmar/monodepth_benchmark#getting-started)).

The second error is caused by the devkit checks, to make sure that we have the expected datasets. If you are still processing the `kitti_raw_lmdb` dataset (or you aren't planning on using it), you should be able to comment out [these lines](https://github.com/jspenmar/monodepth_benchmark/blob/6ad716959030f53f660bfe692796528efa7dc259/src/devkits/kitti_raw_lmdb.py#L17) in the devkit. 

Hope this helps!

**Comment by gmberton** [comment]
Thanks for the quick response!
Instead of commenting those lines, I would like to download all datasets in all their subparts.
So I tried to run the generation of `lmdb` following [this](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md#generate-lmdbs-optional), but it says that I need  syns_patches as well.
Precisely the error is `KeyError: "Missing 'syns_patches' root paths. Got ['kitti_raw', 'kitti_raw_lmdb', 'kitti_depth']."`
So then I tried to download `syns_patches` following [this](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md#syns-patches) but it doesn't work. I think that section is missing a `mkdir syns_patches; cd syns_patches`, and moreover the file `download_syns_patches.py` does not exist.
If I may, I would advise to reorganize the [README](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md) in a chronological manner, so that if one executes all commands in order they should run smoothly (e.g. I would move the [Download section](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md#download) at the beginning, before the [Tests section](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md#tests)).

**Comment by jspenmar** [comment]
Hmm I'm not sure if changing the order would fix this, since the check should run for all devkits when importing the code. I think the easiest solution might be to create placeholder directories for each dataset before trying to download them.
I'll add a note to the README. 

Regarding SYNS-Patches, it is [`download_syns_patches.sh`](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/download_syns_patches.sh), not`.py`! In this case, the zip file will contain the `syns_patches` directory already, so there is no need to `cd` into a new one. 

Thanks for the feedback!

**Comment by gmberton** [comment]
Thanks, I see that you added the [download_syns_patches.sh](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/download_syns_patches.sh), now it works!
One last minor thing, at [SYNS-Patches](https://github.com/jspenmar/monodepth_benchmark/blob/main/api/data/README.md#syns-patches) running 
```
cd $REPO_ROOT/data
../../api/data/download_syns_patches.sh
```
leads to a `No such file or directory`, I think it should be `../api/data/download_syns_patches.sh` or it should be launched from another directory
