### ISSUE TITLE
Evaluation Scripts and Pretrained Weights

### ISSUE THREAD

**Issue by ldkong1205** [jspenmar/monodepth_benchmark#2]
Hi @jspenmar, thank you for open-sourcing this project, it is exciting!

Regarding the re-implemented models, will you release the evaluation scripts as well as the pretrained weights for reproduction? Thanks!

**Comment by jspenmar** [comment]
Hi, glad to hear! 

The evaluation scripts are already available [here](https://github.com/jspenmar/monodepth_benchmark/tree/main/api/eval). Currently the main datasets for evaluation are Kitti Eigen and Kitti Eigen-Benchmark, since the ground-truth for SYNS-Patches is withheld for the WACV challenge we are running. 

In terms of pretrained models, we are still not sure what we will do. We currently have ~60GB of models, since each method has been trained three times.

**Comment by ldkong1205** [comment]
Hi @jspenmar, thank you so much for your prompt and detailed reply!

For the pretrained models, I would like to ask if it is applicable for you to share the pretrained weights on KITTI with me. I am now building benchmarks for depth estimation robustness and I believe your reproduced weights that are improved and unified will be valuable and of great help to my current project. Thanks a lot!

**Comment by jspenmar** [comment]
Hi, sorry for the late reply! 

Is there a specific model you would be interested in trying? I think we are currently unable to share the weights for all different models, but I can maybe try sending one or two specific variants.

**Comment by ldkong1205** [comment]
> Hi, sorry for the late reply!
> 
> Is there a specific model you would be interested in trying? I think we are currently unable to share the weights for all different models, but I can maybe try sending one or two specific variants.

That would be great! Could you please share first the checkpoints of Johnston & Carneiro (CVPR'20) and SuperDepth (ICRA'19)? Thanks a lot for your help!

**Comment by jspenmar** [comment]
I've sent you an email with the links to Google Drive! Hope this helps

**Comment by ldkong1205** [comment]
> I've sent you an email with the links to Google Drive! Hope this helps

The links are well received! Thanks again for your inspiring work!
